version: '3'
services:
  openresty:
      image: openresty/openresty:1.13.6.1-alpine
      restart: always
      tty: true
      volumes:
        - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      ports:
        - 8001:80
      networks:
        - web
  java:
      build:
        context: ./java
        args:
          JAR_FILE: demo-0.0.1-SNAPSHOT.jar
      restart: always
      tty: true
      ports:
        - 8101:8080
      networks:
        - web
  ssdb:
      build:
        context: ./ssdb
      restart: always
      tty: true
      volumes:
        - ./ssdb/ssdb.conf:/usr/local/ssdb/ssdb.conf
      ports:
        - 8201:8888
      networks:
        - web
  ssdb2:
      build:
        context: ./ssdb
      restart: always
      tty: true
      volumes:
        - ./ssdb/ssdb.conf:/usr/local/ssdb/ssdb.conf
      ports:
        - 8202:8888
      networks:
        - web
  ssdb-admin:
      build:
        context: ./ssdb-admin
      command: python app.py
      restart: always
      tty: true
      ports:
        - 8401:5000
      networks:
        - web

networks: 
  web:
    driver: bridge